### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by kakoni** [kamatama41/embulk-output-multi#19]
Hi and thank you for very useful plugin.
I ran few tests with
```yaml
  outputs:
    - type: postgresql
..
    - type: file
```

But after few million lines I always ran into

```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:178)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:436)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
        at org.embulk.cli.Main.main(Main.java:64)
```

I tried with increasing heap sizes (```-J-Xms4096m -J-Xmx4096m```) with no luck.
Running the same tests with just one output (file or postgresql) works fine.

**Comment by kamatama41** [comment]
Hi @kakoni 
Thank you for your report! I have tried fixing it. 
Please try `v0.4.1` works fine on your environment.

**Comment by kakoni** [comment]
Hi @kamatama41.
Yes, this does the job. Excellent!
